#!/bin/bash

# set -x

export COMPOSE_PROJECT_NAME=ld$1
shift

# define a log output function
show_logs() { # shows the last 5 minutes of logs for the lsmb container
    cat <<-EOF
	
	======================================
	
	EOF

    sleep 5; # need a little time for the logs to get updated unfortunately
    docker logs --since $(( `date "+%s"` - (5*60) )) "${COMPOSE_PROJECT_NAME}_lsmb_1";

    cat <<-EOF
	
	======================================
	
	EOF

}

is_container_running() {
    local z;
    z=`docker ps --filter "status=running" --filter="name=${COMPOSE_PROJECT_NAME}_lsmb_1" --quiet 2>/dev/null`;
    test -n "$z";
}

show_result() {
    if is_container_running; then
        cat <<-EOF
	
	======================================
	== LedgerSMB '$CurrentBranch'
	== should be available at
	======================================
	http://${IpAddr}
	======================================
	
	EOF
        return 0
    else
        show_logs
        return 9
    fi
}

# Check we are actually in a LedgerSMB repo
DirName=`git rev-parse --show-toplevel`; # retrieve the git toplevel dir
CurrentBranch=`git rev-parse --abbrev-ref HEAD`
if ! test -r "${DirName}/lib/LedgerSMB.pm"; then
    cat <<-EOF
	========================================
	== ERROR  ERROR  ERROR  ERROR  ERROR  ==
	========================================
	== You don't appear to be running me  ==
	== from a valid LedgerSMB repository  ==
	========================================
	
	EOF
    exit 9
fi

# Check for a local (non repo) version of the yml file
if test -r docker-compose-local.yml; then
    F="$(dirname $(perl -e "use Cwd qw(realpath); print realpath '$0'"))/docker-compose-local.yml"
else
    F="$(dirname $(perl -e "use Cwd qw(realpath); print realpath '$0'"))/docker-compose.yml"
fi

# generate and start the containers
USER="$UID:$GID" docker-compose -f "$F" "$@"

if test "$1" = "start" -o "$1" = "restart" -o "$1" = "up" ; then
  # don't try to report the ip and url if the command is one of
  # pull, rm, stop,

  # report the IP address in the form of a URL
  IpAddr=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "${COMPOSE_PROJECT_NAME}_proxy_1"`

  show_result
fi

if ! test -e Makefile.local ; then
    cat >Makefile.local <<-EOF
	CONTAINER=${COMPOSE_PROJECT_NAME}_lsmb_1
	#PHERKIN_EXTRA_OPTS=--theme=light
	#DOCKER_CMD=
	#PHERKIN_OPTS=

	EOF

    echo "Created Makefile.local causing e.g. 'make test' to run in the container"
else
    if test -z "`grep ${COMPOSE_PROJECT_NAME}_lsmb_1 Makefile.local`" ; then
        echo "'Makefile.local' missing reference to container '${COMPOSE_PROJECT_NAME}_lsmb_1\nplease update it manually"
    fi
fi
