services:

  operablink:
    image: selenium/node-opera:3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
    networks:
      - grid
