services:

  chrome:
    image: selenium/node-chrome:3
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
    networks:
      - grid
