version: '3.2'

services:

  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
    networks:
      - grid
